events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    client_max_body_size 0;

    server {
        listen 80;
        server_name _;

        location / {
            root /usr/share/nginx/html; # * Nginx goes to this directory, and looks for index.html file.
            try_files $uri $uri/ /index.html;
            index index.html index.htm;
        }

        location /shoham/ {
            rewrite ^/shoham(/.*)$ $1 break;
            proxy_pass http://index-server:3000; # * Requests sent by the frontend to "/shoham/* will be proxied to the index-server service in k8s.
        }

    }
}