apiVersion: v1
kind: Service
metadata:
  name: index-client
  labels:
    app: index-client
spec:
  selector:
    app: index-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP