version: '3.8'

services:
  index-client:
    build: client
    image: index_client
    platform: linux/amd64
    ports:
      - '80:80'
    depends_on:
      - index-server

  index-server:
    build: server
    image: index_server
    platform: linux/amd64
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=host.docker.internal
      - DB_NAME=indexhive
      - DB_USER=postgres
      - DB_PASS=postgres
      - NODE_ENV=development
      - JWT_SECRET_TOKEN=o1rjoro1ojrji1i2trnjti3ntiitj23ti3toi322tt32
      - JWT_REFRESH_TOKEN=x9kQmP7R4sT8vE1LJ5nC6D0HfWZB3yUuMGrpx286dsq1
      - S3_BUCKET=indexhive
      - S3_REGION=us-east-1
      - S3_ENDPOINT=http://host.docker.internal:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - SSH_HOST=
      - SSH_USER=guide
      - SSH_PASSWORD=guide
    depends_on:
      - minio
      - index-docs

  index-docs:
    build: Service
    image: index_docs
    platform: linux/amd64
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/indexhive
      - S3_BUCKET=indexhive
      - S3_REGION=us-east-1
      - S3_ENDPOINT=http://host.docker.internal:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
    depends_on:
      - minio

  minio:
    image: minio/minio:latest

    ports:
      - "9000:9000"   
      - "9001:9001"   

    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

    volumes:
      - minio_volume:/data

    command: server /data --console-address ":9001"

volumes:
  minio_volume: